#!/usr/bin/env ruby
#
# Even Fibonacci numbers
# http://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#

class Array
  def even
    select {|x| x % 2 == 0 }
  end

  def sum
    inject(:+)
  end
end

def fibonacci_upto(max)
  result = [1, 2]
  result << result[-1] + result[-2] until result[-1] >= max
  result
end

p fibonacci_upto(4e6).even.sum
# => 4613732
